#all
all:
	gcc -lm getCount.c stopwordFunction.c
socket:
	gcc -lm getKeyword.c stopwordFunction.c
tag:
	gcc -lm -g tagKeyword.c stopwordFunction.c -o tagKeyword
co:
	gcc -lm -g getCocurrence.c stopwordFunction.c -o getCocurrence
re:
	gcc -g countRelatedCorpus.c -o countRelatedCorpus
hashget_re:
	gcc hashget_relatedCorpus.c -o hashget_relatedCorpus
